_target_: engine.engine.Engine
learning_rate: 0.001
n_batch_samples: 256
n_epochs: 2
weight_decay_factor: 0.0001
momentum_coefficient: 0.5
n_train_batch_size: 10
n_test_batch_size: 10
n_valid_batch_size: 10
