# @package _group_
run_exact_cross_check: 1
n_visible: 2
n_hidden: 2
n_betas: 10

n_ais_chains: 1000
load_rbm_from_file: 
  #/Users/drdre/codez/qVAE/DiVAE/output/210324_eps/rbm_1010.pkl

#set by  hydra
output_path: ???