tag: default
debug: False
load_data_from_pkl: 0
load_model: 0
save_model: 0
save_state: 0
load_state: 0
run_path: /home/akajal/DiVAE/outputs/2021-09-05/15-12-41/wandb/run-20210905_151242-o5jp2qc9/files/GumBoltCaloV5_calo_default.pth
input_model: 
create_plots: 0
#output path is set in code to hydra's current working directory
#variable is then used downstream to set paths.
device: gpu
#device: cpu
hp_scan: 1
gpu_list:
  - 0

task:
  - train
  - validate

defaults:
  - model: gumboltcaloV
  - data: calo_cedar
  - engine: dvaecalo_training
    #- override hydra/launcher: submitit_local
  - override hydra/launcher: submitit_slurm
    #this is important - it enables the behaviour that all default configs are overwritten by items listed in this yaml file.
    # see https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/
  - _self_


hydra:
    launcher:
        nodes: 1
        tasks_per_node: 1
        cpus_per_task: 1
        gpus_per_task: 1
        mem_per_gpu: 4000M
        additional_parameters:
            account: def-doneil_gpu
            #account: ctb-stelzer
            time: 00-05:00:00
    sweep:
        dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-XX}/${data.particle_type}
        subdir: ${hydra.job.num}--${hydra.job.override_dirname}

    job:
      config:
          override_dirname:
              kv_sep: ".."
              item_sep: "--"
              exclude_keys:
                  - data.particle_type
                  - data.scaler_path
                  - data.scaler_amin
